### ISSUE TITLE
Cross check whether all software packages are described (in dietpi-software.html)

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Website#20] opened 2020-12-19 15:07 UTC
Check with all softwares on this site  
<https://dietpi.com/docs/software/>  
whether there are softwares which are not described on this site
<https://dietpi.com/dietpi-software.html>
and list them in this issue.

Afterwards, all missing packages need to be described.

Additionally, check for removed packages. E.g. Cloudshell is removed in DietPi 6.34 and exists within dietpi-software.html.

**Comment by MichaIng** [comment] 2020-12-19 15:27
Basically a duplicate of? #13 😃

DietPi-CloudShell has been removed from `dietpi-software` indeed, however the script exists and the documentation about it is valid. But mid-term it should be moved to DietPi tools section of the docs to avoid confusion.

**Comment by StephanStS** [comment] 2020-12-20 21:07
@MichaIng: Yes and no (duplicate of #13).  
This issue is only to check and list the missing items.

Additionally, I changed the issue heading to the right wording (complement != complete).

**Comment by StephanStS** [comment] 2020-12-20 21:11
Software titles available within [`dietpi-software`](https://github.com/MichaIng/DietPi/blob/master/dietpi/dietpi-software), but missing in https://dietpi.com/dietpi-software.html  
(package title | ID):
- GIMP      174
- Xfce4 Power       175
- Squeezelite       36
- MPD       128
- Spotify Connect Web       141
- Allo      159
- Allo_update       160
- Raspotify       167
- Komga       179
- Jellyfin      178
- Nextcloud Talk      168
- FuguHub       161
- Firefox Sync Server       177
- Bitwarden_RS      183
- PaperMC       181
- Docker      162
- Portainer       185
- I2C       72
- Mycroft AI      176
- SQLite      87
- MariaDB       88
- PHP       89
- Redis       91
- Unbound       182
- WireGuard       172
- Tor Relay       184
- EmonPi      99
- Domoticz      140
- TasmoAdmin      27


Software titles available within https://dietpi.com/dietpi-software.html, but missing in [`dietpi-software`](https://github.com/MichaIng/DietPi/blob/master/dietpi/dietpi-software):
- Cloudshell


General questions:
- Certbot       92
  Should it be renamed to "Let's Encrypt"?

- All "Additional linux software items" in the dietpi-software script
  Shall they be described?
  e.g. MC, Python3, node.js, git client, emacs,...

**Comment by fpetru** [comment] 2020-12-20 21:44
While indeed _Certbot_ is the open source software tool that helps to generate the certificates, _Let's Encrypt_ is the thing that anyone searches for. I would say that we should rename it.

**Comment by MichaIng** [comment] 2020-12-20 21:47
Okay, great to have an overview 👍.

> - Certbot 92
Should it be renamed to "Let's Encrypt"?

Nope, what is installed is the Certbot acme client. Let's Encrypt is the CA that can be issued with other clients. E.g. I aim to add the much faster/lightweight acme.sh soon: https://github.com/MichaIng/hacks/blob/main/install_acme.sh

> - All "Additional linux software items" in the dietpi-software script
Shall they be described?
e.g. MC, Python3, node.js, git client, emacs,...

I would say so. We aim this for the programming languages, so why not do this consequently for everything we offer, including a documentation page. This fits to the plan to merge "optimised" and "additional" software lists.

> - Squeezelite 36

I think it is currently merged with Logitech Media Server, but should be separated.

**Comment by fpetru** [comment] 2020-12-20 21:54
Based on the explanation, yes I agree with _Let's encrypt_ approach, as well as with the idea of going towards a merged software list.

**Comment by fpetru** [comment] 2020-12-20 22:03
@StephanStS - shall we update the most recent items with higher priority ? If we create first a smaller PR, and then do the an additional with the rest of changes ? If we do so, anyone searching new things published with latest 3 versions (v6.34 - v6.32), could find them docs (`dietpi-software`).

**Comment by StephanStS** [comment] 2020-12-21 08:07
@fpetru: I would propose these as to be done first:
* Squeezelite       36
* MPD       128
* Spotify Connect Web       141
* Raspotify       167
* Komga       179
* Jellyfin      178
* Nextcloud Talk      168
* FuguHub       161
* Bitwarden_RS      183
* PaperMC       181
* Docker      162
* Portainer       185
* SQLite      87
* MariaDB       88
* PHP       89
* Unbound       182
* Tor Relay       184

**Comment by MichaIng** [comment] 2020-12-21 11:28
FuguHub is missing in docs as well: https://github.com/MichaIng/DietPi-Docs/issues/238

**Comment by JappeHallunken** [comment] 2022-04-03 19:32
**Listed in https://dietpi.com/docs/software/, but not in https://dietpi.com/dietpi-software.html:**

Advanced Networking 
⦁	frp

Gaming & Emulation
⦁	PaperMC - Fast and optimized Minecraft server
⦁	Box86 - i386 userspace emulation for ARMv7
⦁	Box64 - x86_64 userspace emulation for ARMv8

BitTorrent & Download Tools
⦁	youtube-dl - download videos from YouTube and other sites

Camera & Surveillance¶
⦁	mjpg-streamer - Simple camera streaming tool with HTML plugin

Cloud & Backup systems
⦁	Nextcloud Talk - Video calls via Nextcloud, including TURN server
⦁	Firefox Sync Server - Sync bookmarks, tabs, history and passwords
⦁	vaultwarden - Unofficial Bitwarden password manager server written in Rust
⦁	FuguHub - Your Own Personal Cloud Server
⦁	File Browser - Light web based file manager with sharing features

Databases & Data Stores
⦁	MariaDB
⦁	SQLite - Small, Fast and High reliable SQL database engine
⦁	Redis - Open Source In-memory key–value Data Store
⦁	PostgreSQL - Persistent and advanced SQL database engine

Desktop Utilities
⦁	Firefox - Web browser
⦁	GIMP - Image editor
⦁	QuiteRSS - RSS and Atom news feeds reader
⦁	Xfce Power Manager - Power manager with brightness control

Development & Programming¶

⦁	    Python 3 - High-level interpreted programming language
⦁	Go - Programming language
⦁	Docker - Build, ship, and run distributed applications
⦁	Docker-Compose - Run multi-container applications on Docker
⦁	Portainer - Docker container management
⦁	VSCodium - FLOSS version of Microsoft VSCode

Distributed Projects¶
⦁	Tor Relay - Add a node to the Tor network

DNS Servers¶
⦁	Unbound - A validating, recursive, and caching DNS resolver
⦁	AdGuard Home - A powerful network-wide ads & trackers blocking DNS server

Hardware Projects¶
⦁	Mycroft AI - Open source voice assistant

Home Automation
⦁	Domoticz - Multi platform Home Automation System
⦁	TasmoAdmin - Administrative website for Tasmota devices

Media Systems
⦁	Squeezelite - Audio player for Logitech Media Server
⦁	Komga - Free and open source comics/mangas media server with web UI
⦁	Raspotify - Spotify Connect client
⦁	Spotify Connect Web - Web interface, client and player for Spotify Premium
⦁	Spotifyd - Lightweight FOSS Spotify client
⦁	Jellyfin - Media streaming server including live TV
⦁	Beets - Music organizer and manager
⦁	Snapcast Server - Multi room audio server
⦁	Snapcast Client - Multi room audio client

Printing Server¶
⦁	    CUPS - Common UNIX printing system

Social & Search¶ 
⦁	Synapse - Decentralized communication with the Matrix protocol

System Security¶
⦁	    Let’s Encrypt - Enable HTTPS / SSL

System Stats & Management¶
⦁	DietPi-Dashboard - Official lightweight standalone DietPi web interface
⦁	K3s - Lightweight Kubernetes
⦁	MicroK8s - Low-ops, minimal production Kubernetes

VPN
⦁	WireGuard - An extremely simple yet fast and modern VPN

Programming & Web development Frameworks¶
⦁	Flask - Micro web framework powered by Python


(
Stacks for web development¶
⦁	    LAMP web stack - Apache / MariaDB / PHP
⦁	    LASP web stack - Apache / SQLite / PHP
⦁	    LEMP web stack - Nginx / MariaDB / PHP
⦁	    LESP web stack - Nginx / SQLite / PHP
⦁	    LLMP web stack - Lighttpd / MariaDB / PHP
⦁	    LLSP web stack - Lighttpd / SQLite / PHP
)


**Listed in in https://dietpi.com/dietpi-software.html, but not in https://dietpi.com/docs/software/:**

Hardware Projects¶
⦁	   InfluxDB

Web Server Stacks
⦁	   Certbot


Listed in `dietpi-software`, but missing on both sites:
x11, alsa, unrar, ffmpeg
midnight commander, ViFM
the complete network tools and other dependencies like git, JDK, go
the texteditors emacs, jed, vim, vim-tiny, neovim

IDK if it is worth listing all of them?!

**Comment by MichaIng** [comment] 2022-04-03 22:18
Many thanks for collecting it.

**Comment by JappeHallunken** [comment] 2023-01-26 17:39
The missing titles from https://github.com/MichaIng/DietPi-Website/issues/20#issuecomment-1086933615 are now integrated. I will make a PR soon (https://github.com/MichaIng/DietPi-Website/compare/master...JappeHallunken:DietPi-Website:master)

Still some inconsistencies:

- Listed in dietpi-software.html but not in the docs: OpenBazaar.

- Node.js, Python 3, Go and PHP composer are now present in both documents.

**Comment by MichaIng** [comment] 2023-01-26 23:11
> Listed in dietpi-software.html but not in the docs: OpenBazaar.

OpenBazaar has been removed a while ago, hence should be removed from `dietpi-software.html` as well.

> Node.js, Python 3, Go and PHP composer are now present in both documents.

Awesome 👍!

**Closed** 2023-02-07 21:05 UTC
Labels: dietpi-software.html
